130 storage firebase
fga-eps-mds/2021.1-Multilind-files-server pull request #4
Opened 2021-09-23 01:08 UTC by F1reFinger

## Description 

Firebase Storage created and working

## Solve (Issues)

#130

## Tasks done with this PR

created an project in firebase
Download an SDK from firebase
Configuration - credentials e init

2021-09-23 02:46 UTC, micaellagouveia requested changes

2021-09-23 02:46 UTC, micaellagouveia commented on src/config/storage.js
> +const admin = require("firebase-admin");
Utilizar notação de import from

2021-09-23 02:46 UTC, micaellagouveia commented on src/config/storage.js
> +const serviceAccount = require("../../serviceAccountKey.json");
Utilizar notação de import from

2021-09-23 02:46 UTC, micaellagouveia commented on src/controllers/File/createFile.js
> +import bucket from "../../config/storage";
Aqui vc pode trocar essa rota "../../config/storage" por ~/config/storage (ou  ~/src/config/storage não me lembro qual o certo kkk). Assim vc consegue acessar a raiz do projeto e não precisa ficar voltando pra trás.

2021-09-23 02:46 UTC, micaellagouveia commented on src/controllers/File/getAllFile.js
> +import bucket from "../../config/storage";
Aqui vc pode trocar essa rota "../../config/storage" por ~/config/storage (ou ~/src/config/storage não me lembro qual o certo kkk). Assim vc consegue acessar a raiz do projeto e não precisa ficar voltando pra trás.

2021-09-23 02:46 UTC, micaellagouveia commented on src/controllers/File/getAllFile.js
> +export async function getAll(request, response) {
colocar no padrão (req, res)

2021-09-23 02:46 UTC, micaellagouveia commented on src/controllers/File/getAllFile.js
> +  const { id_palavra } = params;
Aqui não tem necessidade de desconstruir request em params para depois descontruir em id_palavra, já que vc não vai utilizar o params. Pode apenas desconstruir assim: const { id_palavra } = req.params

2021-09-23 02:46 UTC, micaellagouveia commented on src/routes/File/file.routes.js
> +import { getAll, create } from "../../controllers/File";
Aqui pode ser utilizada a notação ~/controllers/File
Colocar todos os imports em cima e deixar o Router() depois de todos os imports.

2021-09-23 02:46 UTC, micaellagouveia commented on src/routes/index.js
> +const fileUpload = require("express-fileupload");
utilizar notação import from

2021-09-23 03:06 UTC, GabrielDVpereira commented on src/controllers/File/createFile.js
> +import bucket from "../../config/storage";
nesse caso ele teria que configurar um alias, dá pra fazer usando o babel, mas n sei se seria escencial

2021-09-23 17:31 UTC, micaellagouveia submitted a review, later dismissed

2021-09-26 14:20 UTC, micaellagouveia approved these changes

2021-09-27 00:03 UTC, merged